title = "Case study 1 with the Choucas Alert Ontology"

covikoa-vocabularies = [
  "./rdf/voc-hh-graphic.ttl",
  "./rdf/voc-hh-symbol.ttl",
  "./rdf/voc-hh-symbolizer.ttl",
  "./rdf/voc-hh-scale.ttl",
  "./rdf/voc-context.ttl",
  "./rdf/voc-geoviz.ttl",
  "./rdf/voc-derivation.ttl",
]

target-semantic-data-model-files = [
  "./rdf/loac/light-oac.ttl",
  "./rdf/loac/loac-reference-objects.ttl",
  "./rdf/case_study_3/data-alert-loac.ttl",
]

derivation-model = "./rdf/case_study_3/derivation-model-loac.ttl"


[geospatial-triplestore]
model = "./rdf/loac/loac-reference-objects.ttl"
data = "./rdf/loac/data-loac-reference-objects.ttl"
