title = "Case study 2 with the Choucas Alert Ontology, near Chantepérier"

covikoa-vocabularies = [
  "./rdf/voc-huang-graphic.ttl",
  "./rdf/voc-huang-symbol.ttl",
  "./rdf/voc-huang-symbolizer.ttl",
  "./rdf/voc-huang-scale.ttl",
  "./rdf/voc-context.ttl",
  "./rdf/voc-geoviz.ttl",
  "./rdf/voc-derivation.ttl",
]

target-semantic-data-model-files = [
  "./rdf/loac/light-oac.ttl",
  "./rdf/loac/loac-reference-objects.ttl",
  "./rdf/case_study_2/data-alert-loac.ttl",
]

derivation-model = "./rdf/case_study_2/derivation-model-loac.ttl"


[geospatial-triplestore]
model = "./rdf/loac/loac-reference-objects.ttl"
data = "./rdf/loac/data-loac-reference-objects.ttl"
